# Site settings
title: Giving
email: givingtoken@gmail.com
url: https://givingtoken.github.io/
description: "Giving token is ethereum smart contract that is liked by many internet users."
address: "Address: <a href="https://etherscan.io/token/0x031228f403dbfde1dd47310bdc49bb788f53ecd9" class="btn btn-lg btn-outline">0x031228f403dbfde1dd47310bdc49bb788f53ecd9</a>

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Giving Token

# Build settings
markdown: kramdown
permalink: pretty
